/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Jun 26 2018 09:35:00 GMT-0500 (Central Daylight Time).
 */

define([
    'q',
    'common/util/ejs',
    'js/Constants',
    'text!comif-hems/domain.txt'
], function (
    Q,
    ejs,
    CONSTANTS,
    domainTxt
) {

    'use strict';

    var FormulaConstraintEditorControl;

    FormulaConstraintEditorControl = function (options) {
        var self = this;

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        this._widget = options.widget;
        this._currentNodeId = null;
        this._gatheringSegments = false;
        this._missedEvents = false;

        this._territory = null;
        this._segmentInfo = {};
        this._UID = this._client.addUI(self, function (events) {
            self._eventCallback(events);
        });

        this._initWidgetEventHandlers();

        console.log(domainTxt);
        this._logger.debug('ctor finished');
    };

    FormulaConstraintEditorControl.prototype._initWidgetEventHandlers = function () {
        var self = this;
        this._widget.onSave = function (segmentedDocumentObject) {
            // console.log(segmentedDocumentObject);
            self._SaveDocument(segmentedDocumentObject);
        };
    };

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    FormulaConstraintEditorControl.prototype.selectedObjectChanged = function (nodeId) {
        var node = this._client.getNode(nodeId);

        if (node) {
            //we have a viable component type so let us change things
            this._currentNodeId = nodeId;
            this._selfPatterns = {};
            this._selfPatterns[nodeId] = {children: -1};
            this._client.updateTerritory(this._UID, this._selfPatterns);
        } else {
            this._logger.info('received unwanted object change event');
        }
    };


    /* * * * * * * * Node Event Handling * * * * * * * */
    FormulaConstraintEditorControl.prototype._eventCallback = function (events) {
        var self = this,
            i = events ? events.length : 0,
            event;

        this._logger.debug('_eventCallback \'' + i + '\' items');

        this._buildSegmentInfo(this._currentNodeId)
            .then(function (segmentedDocument) {
                self._widget.setSegmentedDocument(segmentedDocument);
            });
        this._logger.debug('_eventCallback \'' + events.length + '\' items - DONE');
    };

    FormulaConstraintEditorControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    /* * * * * * * * Segmented Document Handling * * * * * * * */
    FormulaConstraintEditorControl.prototype._getSegmentOffset = function (segmentedDocument, segmentId) {
        var compiledText = '',
            index = 0,
            sId = segmentedDocument.composition[0] || null;

        while (sId !== null && sId !== segmentId && index < segmentedDocument.composition.length) {
            compiledText += segmentedDocument.segments[sId].value + '\n';
            sId = segmentedDocument.composition[++index];
        }

        return compiledText.split('\n').length;
    };

    FormulaConstraintEditorControl.prototype._buildSegmentInfo = function (nodeId) {
        var self = this,
            node = self._client.getNode(nodeId),
            deferred = Q.defer(),
            segmentedDocument = {
                composition: [],
                segments: {},
                errors: []
            };

        if (node === null) {
            deferred.resolve(segmentedDocument);
            return deferred.promise;
        }

        segmentedDocument.composition = ['domainStart', 'user', 'domainEnd', 'modelMeta', 'modelNodes'];
        segmentedDocument.segments.domainStart = {
            value: 'Here are the beggining of the domain\n...\n...\nand comes the user part\n...',
            options: {readonly: true}
        };
        segmentedDocument.segments.user = {
            value: self._client.getNode(self._currentNodeId).getAttribute('_formula_constraints') || '',
            options: {readonly: false}
        };
        segmentedDocument.segments.domainEnd = {
            value: '// end of the WebGME domain definition\n}\n\n',
            options: {readonly: true}
        };
        segmentedDocument.segments.modelMeta = {
            value: 'model watta of WebGME\n{\n...\n...',
            options: {readonly: true}
        };
        segmentedDocument.segments.modelNodes = {
            value: 'and the nodes\n...\n...\n}\n\n',
            options: {readonly: true}
        };
        deferred.resolve(segmentedDocument);
        return deferred.promise;
    };

    FormulaConstraintEditorControl.prototype._SaveDocument = function (changedSegments) {
        if (changedSegments.hasOwnProperty('user')) {
            this._client.setAttribute(this._currentNodeId, '_formula_constraints', changedSegments.user);
        }
    };
    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    FormulaConstraintEditorControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
    };

    FormulaConstraintEditorControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    FormulaConstraintEditorControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    FormulaConstraintEditorControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    FormulaConstraintEditorControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
    };

    /* * * * * * * * * * Updating the toolbar * * * * * * * * * */
    FormulaConstraintEditorControl.prototype._displayToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].show();
            }
        } else {
            this._initializeToolbar();
        }
    };

    FormulaConstraintEditorControl.prototype._hideToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].hide();
            }
        }
    };

    FormulaConstraintEditorControl.prototype._removeToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].destroy();
            }
        }
    };

    FormulaConstraintEditorControl.prototype._initializeToolbar = function () {
        var self = this,
            toolBar = WebGMEGlobal.Toolbar;

        this._toolbarItems = [];

        this._toolbarItems.push(toolBar.addSeparator());

        this.$btnSave = toolBar.addButton({
            title: 'Save changes',
            icon: 'glyphicon glyphicon-floppy-disk',
            clickFn: function (/*data*/) {
                self._SaveDocument(self._widget.getChangedSegments());
            }
        });
        this._toolbarItems.push(this.$btnSave);

        this.$btnCheck = toolBar.addButton({
            title: 'Check model conformance',
            icon: 'glyphicon glyphicon-eye-open',
            clickFn: function (/*data*/) {
                console.log('we need to call the formula checking here');
            }
        });
        this._toolbarItems.push(this.$btnCheck);


        this._toolbarInitialized = true;
    };

    return FormulaConstraintEditorControl;
});
