/*globals define*/
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.16.0 from webgme on Wed Jun 27 2018 11:03:44 GMT-0500 (Central Daylight Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'plugin/PluginMessage',
    'comif-hems/clientUtils',
    'text!comif-hems/domain.txt'
], function (PluginConfig,
             pluginMetadata,
             PluginBase,
             PluginMessage,
             utils,
             domainTxt) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of GremlinConformanceCheck.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin GremlinConformanceCheck.
     * @constructor
     */
    var GremlinConformanceCheck = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    };

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructue etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    GremlinConformanceCheck.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    GremlinConformanceCheck.prototype = Object.create(PluginBase.prototype);
    GremlinConformanceCheck.prototype.constructor = GremlinConformanceCheck;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    GremlinConformanceCheck.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            GREMLINDIR = 'C:\\gremlin-console\\',
            exec = require('child_process').exec,
            fs = require('fs'),
            path = require('path'),
            filename = self._getRandomFileName(),
            filePath = path.resolve(process.cwd(), filename);

        self._createProjectFile(filename + '.out', function (err, projectFile) {
            if (err) {
                self.logger.error(err);
                self.result.setSuccess(false);
                callback(null, self.result);
                return;
            }

            fs.writeFileSync(filename + '.groovy', projectFile, 'utf8');

            exec('gremlin.bat ' + filePath + '.groovy', {}, function (err, stdout, stderr) {
                fs.unlinkSync(filePath + '.groovy');
                var result = false;
                try {
                    var file = fs.readFileSync(GREMLINDIR + filename + '.out', 'utf8');
                    result = file.indexOf('true') !== -1;
                    fs.unlinkSync(GREMLINDIR + filename + '.out');
                } catch (e) {
                    result = false;
                }

                if (err) {
                    self.logger.error(err);
                    self.result.setSuccess(false);
                    callback(null, self.result);
                    return;
                }
                self.result.setSuccess(result);
                callback(null, self.result);
            });

        });

    };

    GremlinConformanceCheck.prototype._createProjectFile = function (filePath, callback) {
        var self = this,
            core = self.core,
            path = core.getPath(self.activeNode),
            root = core.getRoot(self.activeNode),
            name = core.getAttribute(self.activeNode, 'name'),
            input = self.getCurrentConfig().gremlinProjectFile;

        if (input) {
            input += utils.getGremlinSave(filePath);
            callback(null, input);
            return;
        }

        utils.getGremlinData(core, root, path, name, function (err, gremlin) {
            if (err) {
                callback(err);
            } else {
                input = gremlin;
                input += utils.getGremlinSave(filePath);
            }
            callback(null, input);
        });
    };

    GremlinConformanceCheck.prototype._getRandomFileName = function () {
        var chars = 'abcdefghijklmnopqrstuvxyzw',
            length = 8,
            name = '';

        while (length--) {
            name += chars.charAt(Math.floor(Math.random() * chars.length));
        }
        return name;
    };

    return GremlinConformanceCheck;
});
