// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-bip/src/plugins');
config.visualization.decoratorPaths.push(__dirname + '/../node_modules/webgme-bip/src/decorators');
config.seedProjects.basePaths.push(__dirname + '/../node_modules/webgme-bip/src/seeds/BIPv1');



config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-bip/src/visualizers/panels');
config.visualization.panelPaths.push(__dirname + '/../node_modules/webgme-bip-editors/src/visualizers/panels');




// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'BIPExecutionViz': 'panels/BIPExecutionViz/BIPExecutionVizPanel',
  'CrosscutDD': 'panels/Crosscut/CrosscutPanel',
  'SetEditorDD': 'panels/SetEditor/SetEditorPanel',
  'ModelEditorDD': 'panels/ModelEditor/ModelEditorPanel',
  'BIPCodeEditor': 'panels/BIPCodeEditor/BIPCodeEditorPanel',
  'BIPStateDecorator': 'node_modules\webgme-bip\src\decorators\BIPStateDecorator',
  'BIPConnectorEndDecorator': 'node_modules\webgme-bip\src\decorators\BIPConnectorEndDecorator',
  'BIPComponentTypeDecorator': 'node_modules\webgme-bip\src\decorators\BIPComponentTypeDecorator',
  'BIPv1': 'node_modules\webgme-bip\src\seeds\BIPv1',
  'JavaBIPEngine': 'node_modules\webgme-bip\src\plugins\JavaBIPEngine',
  'BehaviorSpecGenerator': 'node_modules\webgme-bip\src\plugins\BehaviorSpecGenerator',
  'ArchitectureSpecGenerator': 'node_modules\webgme-bip\src\plugins\ArchitectureSpecGenerator',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panels/BIPExecutionViz': './node_modules/webgme-bip-editors/src/visualizers/panels/BIPExecutionViz',
  'widgets/BIPExecutionViz': './node_modules/webgme-bip-editors/src/visualizers/widgets/BIPExecutionViz',
  'panels/Crosscut': './node_modules/webgme-bip-editors/src/visualizers/panels/Crosscut',
  'widgets/Crosscut': './node_modules/webgme-bip-editors/src/visualizers/widgets/Crosscut',
  'panels/SetEditor': './node_modules/webgme-bip-editors/src/visualizers/panels/SetEditor',
  'widgets/SetEditor': './node_modules/webgme-bip-editors/src/visualizers/widgets/SetEditor',
  'panels/ModelEditor': './node_modules/webgme-bip-editors/src/visualizers/panels/ModelEditor',
  'widgets/ModelEditor': './node_modules/webgme-bip-editors/src/visualizers/widgets/ModelEditor',
  'panels/BIPCodeEditor': './node_modules/webgme-bip/src/visualizers/panels/BIPCodeEditor',
  'widgets/BIPCodeEditor': './node_modules/webgme-bip/src/visualizers/widgets/BIPCodeEditor',
  'webgme-bip': './node_modules/webgme-bip/src/common',
  'webgme-bip-editors': './node_modules/webgme-bip-editors/src/common',
  'comif-hems': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/comif_hems';
validateConfig(config);
module.exports = config;
